# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, upload_to='profileImages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=560)),
                ('phone_number', models.CharField(max_length=560)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='venueImages')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
