# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.BooleanField(default=False, verbose_name='isVenue'),
        ),
    ]
