# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 17:07
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime(2019, 2, 26, 17, 6, 8, 123697, tzinfo=utc), verbose_name='Date')),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 2, 26, 17, 6, 8, 123748, tzinfo=utc), verbose_name='Comment Time')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('concertID', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=128)),
                ('Date', models.DateField(verbose_name='Date')),
                ('StartTime', models.DateTimeField(verbose_name='Start Time')),
                ('EndTime', models.DateTimeField(verbose_name='End Time')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='venueImages')),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=560)),
            ],
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='views',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='id',
        ),
        migrations.AddField(
            model_name='venue',
            name='venueID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.Venue'),
        ),
        migrations.AddField(
            model_name='comment',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.Concert'),
        ),
    ]
