# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='endTime',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='startTime',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
