# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concert.Comment'),
        ),
    ]
