# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_comment_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=560, null=True),
        ),
    ]
