# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_auto_20190308_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='artist',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(blank=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.CharField(blank=True, max_length=560),
        ),
        migrations.AlterField(
            model_name='concert',
            name='end_time',
            field=models.TimeField(blank=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='start_time',
            field=models.TimeField(blank=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='concert', to='concert.Venue'),
        ),
    ]
