# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_auto_20190226_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 26, 17, 8, 54, 358901, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 26, 17, 8, 54, 358944, tzinfo=utc), verbose_name='Comment Time'),
        ),
    ]
