# Generated by Django 2.1.7 on 2019-03-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_auto_20190305_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
