# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_auto_20190306_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
