# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0004_auto_20190226_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='venue_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='venue_images'),
        ),
    ]
