# Generated by Django 2.1.7 on 2019-03-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0004_auto_20190305_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_venue',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
