# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0004_auto_20190307_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='url',
            new_name='website',
        ),
    ]
