# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0005_auto_20190313_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='concert.Concert'),
        ),
    ]
