# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0005_auto_20190301_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='photo',
            new_name='image',
        ),
    ]
