# Generated by Django 2.1.7 on 2019-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0005_user_is_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giggoer',
            name='bookmarks',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_venue',
            field=models.BooleanField(default=False),
        ),
    ]
