# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0006_auto_20190301_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activationLey',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emailValidated',
            field=models.BooleanField(default=False),
        ),
    ]
