# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0007_auto_20190313_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['-date']},
        ),
    ]
