# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0007_auto_20190301_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activationLey',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emailValidated',
        ),
    ]
